// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG0eVUua03RYPTBRX9wsvovneOpzI_AXQ',
    appId: '1:106860583414:web:1c153743dd8e0b786e8fd7',
    messagingSenderId: '106860583414',
    projectId: 'agro-suport',
    authDomain: 'agro-suport.firebaseapp.com',
    storageBucket: 'agro-suport.firebasestorage.app',
    measurementId: 'G-YF6C18CTGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYyFX4-iUENc2Wyi2fkVaMWja8gbGm8V8',
    appId: '1:106860583414:android:136c7925511923bb6e8fd7',
    messagingSenderId: '106860583414',
    projectId: 'agro-suport',
    storageBucket: 'agro-suport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsRX9aIdDm4K2PSA2_SDrpRDRw5x4hEO8',
    appId: '1:106860583414:ios:57ddb2a8a9dbf1406e8fd7',
    messagingSenderId: '106860583414',
    projectId: 'agro-suport',
    storageBucket: 'agro-suport.firebasestorage.app',
    iosBundleId: 'com.example.agro',
  );
}
